# Generated by Django 5.1 on 2026-04-02 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACESSO', 'Acesso ao sistema'), ('CRIACAO', 'Criação'), ('ALTERACAO', 'Alteração'), ('EXCLUSAO', 'Exclusão'), ('PUBLICACAO', 'Publicação de resultado'), ('INSCRICAO', 'Inscrição'), ('CANCELAMENTO', 'Cancelamento de inscrição'), ('ENVIO_DOCUMENTO', 'Envio/substituição de documento'), ('AVALIACAO', 'Avaliação'), ('RECURSO', 'Interposição de recurso'), ('RESPOSTA_RECURSO', 'Resposta a recurso'), ('INTEGRACAO', 'Integração externa'), ('PRORROGACAO', 'Prorrogação de prazo'), ('FORMULARIO', 'Preenchimento de formulário')], max_length=30, verbose_name='Tipo de evento')),
                ('acao', models.CharField(max_length=500, verbose_name='Ação executada')),
                ('objeto_tipo', models.CharField(blank=True, max_length=100, verbose_name='Tipo do objeto afetado')),
                ('objeto_id', models.CharField(blank=True, max_length=100, verbose_name='ID do objeto afetado')),
                ('objeto_repr', models.CharField(blank=True, max_length=500, verbose_name='Representação do objeto')),
                ('valor_anterior', models.JSONField(blank=True, null=True, verbose_name='Valor anterior')),
                ('valor_posterior', models.JSONField(blank=True, null=True, verbose_name='Valor posterior')),
                ('origem', models.CharField(blank=True, max_length=255, verbose_name='Origem da ação (IP/endpoint)')),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data e hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Auditoria',
                'verbose_name_plural': 'Eventos de Auditoria',
                'ordering': ['-data_hora'],
            },
        ),
    ]
