services:

    db:
        image: postgres:18-alpine
        environment:
            - POSTGRES_DATABASE=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - "./data/db_backup:/docker-entrypoint-initdb.d"
            - "../volumes/prosel/db/data:/var/lib/postgresql/18/docker"
        healthcheck:
            test: [ "CMD", "psql", "-h", "127.0.0.1", "-U", "postgres" ]
            interval: 3s
            timeout: 3s
            retries: 3
            start_period: 10s

    cache:
        image: valkey/valkey:8.1.1-alpine
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 3s
            timeout: 3s
            retries: 3
            start_period: 10s

    mail:
        image: mailhog/mailhog:latest
        ports:
            - 8025:8025
