# Generated by Django 5.1 on 2026-04-02 19:30

import django.core.validators
import django.db.models.deletion
import inscricoes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número de inscrição')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CANCELADA', 'Cancelada'), ('HABILITADA', 'Habilitada'), ('ELIMINADA', 'Eliminada')], default='ATIVA', max_length=20, verbose_name='Status')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data de inscrição')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de cancelamento')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to=settings.AUTH_USER_MODEL, verbose_name='Candidato')),
                ('fase_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes_na_fase', to='processos.fase')),
                ('processo_seletivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='processos.processoseletivo', verbose_name='Processo Seletivo')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-data_inscricao'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('tamanho_maximo_mb', models.PositiveIntegerField(default=2, help_text='Tamanho máximo do arquivo em megabytes.', verbose_name='Tamanho máximo (MB)')),
                ('tem_pontuacao', models.BooleanField(default=False, help_text='Indica se o candidato pode informar pontuação referencial para este documento.', verbose_name='Possui pontuação')),
                ('pontuacao_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pontuação máxima')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_documento', to='processos.etapa')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['etapa', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=inscricoes.models.documento_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Arquivo')),
                ('pontuacao_informada', models.DecimalField(blank=True, decimal_places=2, help_text='Caráter referencial. Não vinculante.', max_digits=10, null=True, verbose_name='Pontuação informada pelo candidato')),
                ('ativo', models.BooleanField(default=True, verbose_name='Arquivo atual')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='inscricoes.inscricao')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='inscricoes.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-data_envio'],
            },
        ),
    ]
