# Generated by Django 5.1 on 2026-04-02 19:30

import avaliacoes.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscricoes', '0001_initial'),
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nota')),
                ('parecer', models.TextField(blank=True, verbose_name='Parecer')),
                ('aprovado', models.BooleanField(blank=True, null=True, verbose_name='Aprovado')),
                ('atende_requisitos', models.BooleanField(blank=True, null=True, verbose_name='Atende aos requisitos')),
                ('observacoes_banca', models.TextField(blank=True, verbose_name='Observações para banca/coordenadoria')),
                ('observacoes_candidato', models.TextField(blank=True, verbose_name='Observações para o candidato')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa')),
                ('anexo', models.FileField(blank=True, null=True, upload_to=avaliacoes.models.avaliacao_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Anexo')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de avaliação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='processos.etapa')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='inscricoes.inscricao')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data_avaliacao'],
                'unique_together': {('inscricao', 'etapa', 'avaliador')},
            },
        ),
        migrations.CreateModel(
            name='CriterioAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('peso', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Peso')),
                ('mensuravel', models.BooleanField(default=True, help_text='Critérios não mensuráveis exigem ateste de aprovado/reprovado além de nota.', verbose_name='Mensurável')),
                ('nota_maxima', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Nota máxima')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='processos.etapa')),
            ],
            options={
                'verbose_name': 'Critério de Avaliação',
                'verbose_name_plural': 'Critérios de Avaliação',
                'ordering': ['etapa', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('obrigatorio', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_checklist', to='processos.etapa')),
            ],
            options={
                'verbose_name': 'Item de Checklist',
                'verbose_name_plural': 'Itens de Checklist',
                'ordering': ['etapa', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='NotaCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nota')),
                ('aprovado', models.BooleanField(blank=True, null=True, verbose_name='Aprovado no critério')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_criterio', to='avaliacoes.avaliacao')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='avaliacoes.criterioavaliacao')),
            ],
            options={
                'verbose_name': 'Nota por Critério',
                'verbose_name_plural': 'Notas por Critério',
                'unique_together': {('avaliacao', 'criterio')},
            },
        ),
        migrations.CreateModel(
            name='RespostaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcado', models.BooleanField(default=False, verbose_name='Marcado')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_checklist', to='avaliacoes.avaliacao')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='avaliacoes.itemchecklist')),
            ],
            options={
                'verbose_name': 'Resposta de Checklist',
                'verbose_name_plural': 'Respostas de Checklist',
                'unique_together': {('avaliacao', 'item')},
            },
        ),
    ]
