# Generated by Django 5.1.14 on 2026-04-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAutenticacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govbr_habilitado', models.BooleanField(default=True, verbose_name='gov.br habilitado')),
                ('suap_habilitado', models.BooleanField(default=False, verbose_name='SUAP habilitado')),
                ('django_habilitado', models.BooleanField(default=False, verbose_name='Login nativo (Django) habilitado')),
            ],
            options={
                'verbose_name': 'Configuração de Autenticação',
                'verbose_name_plural': 'Configuração de Autenticação',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='suap_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID SUAP'),
        ),
    ]
