# Generated by Django 5.1 on 2026-04-02 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscricoes', '0001_initial'),
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('pontuado', models.BooleanField(default=False, verbose_name='Formulário pontuado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('etapa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formulario', to='processos.etapa')),
            ],
            options={
                'verbose_name': 'Formulário',
                'verbose_name_plural': 'Formulários',
            },
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'Número'), ('DATA', 'Data'), ('SELECAO_UNICA', 'Seleção única'), ('MULTIPLA_SELECAO', 'Múltipla seleção'), ('CHECKBOX', 'Checkbox'), ('UPLOAD', 'Upload')], max_length=20, verbose_name='Tipo')),
                ('rotulo', models.CharField(max_length=255, verbose_name='Rótulo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição/ajuda')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('opcoes', models.JSONField(blank=True, default=list, help_text='Lista de opções para campos de seleção.', verbose_name='Opções')),
                ('pontuacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pontuação máxima')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='formularios.formulario')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
                'ordering': ['formulario', 'ordem'],
                'unique_together': {('formulario', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='RespostaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='formularios.formulario')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_formulario', to='inscricoes.inscricao')),
                ('respondido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas_formulario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resposta de Formulário',
                'verbose_name_plural': 'Respostas de Formulários',
                'unique_together': {('inscricao', 'formulario')},
            },
        ),
        migrations.CreateModel(
            name='RespostaCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.JSONField(blank=True, null=True, verbose_name='Valor')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='formularios.campo')),
                ('resposta_formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_campo', to='formularios.respostaformulario')),
            ],
            options={
                'verbose_name': 'Resposta de Campo',
                'verbose_name_plural': 'Respostas de Campos',
                'unique_together': {('resposta_formulario', 'campo')},
            },
        ),
    ]
