# Generated by Django 5.1 on 2026-04-02 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='papel',
            name='processo_seletivo',
            field=models.ForeignKey(blank=True, help_text='Se nulo, o papel é global (Administrador). Se definido, é específico do processo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papeis', to='processos.processoseletivo'),
        ),
        migrations.AddField(
            model_name='papel',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papeis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='papel',
            unique_together={('usuario', 'tipo', 'processo_seletivo')},
        ),
    ]
