# Generated by Django 5.1 on 2026-04-02 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscricoes', '0001_initial'),
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto do recurso')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_interposicao', models.DateTimeField(auto_now_add=True, verbose_name='Data de interposição')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='processos.etapa')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='inscricoes.inscricao')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-data_interposicao'],
                'unique_together': {('inscricao', 'etapa')},
            },
        ),
        migrations.CreateModel(
            name='RespostaRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto da resposta')),
                ('data_resposta', models.DateTimeField(auto_now_add=True, verbose_name='Data de resposta')),
                ('recurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resposta', to='recursos.recurso')),
                ('respondido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas_recurso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resposta ao Recurso',
                'verbose_name_plural': 'Respostas aos Recursos',
            },
        ),
    ]
