# Generated by Django 5.1 on 2026-04-02 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscricoes', '0001_initial'),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Classificação')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nota final')),
                ('selecionado', models.BooleanField(default=False, verbose_name='Selecionado')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de publicação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_final', to='inscricoes.inscricao')),
                ('processo_seletivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_finais', to='processos.processoseletivo')),
            ],
            options={
                'verbose_name': 'Resultado Final',
                'verbose_name_plural': 'Resultados Finais',
                'ordering': ['classificacao'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nota final')),
                ('habilitado', models.BooleanField(default=False, verbose_name='Habilitado')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de publicação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_etapa', to='processos.etapa')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_etapa', to='inscricoes.inscricao')),
            ],
            options={
                'verbose_name': 'Resultado de Etapa',
                'verbose_name_plural': 'Resultados de Etapa',
                'ordering': ['-nota_final'],
                'unique_together': {('inscricao', 'etapa')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=False, verbose_name='Habilitado')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de publicação')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='processos.fase')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_fase', to='inscricoes.inscricao')),
            ],
            options={
                'verbose_name': 'Resultado de Fase',
                'verbose_name_plural': 'Resultados de Fase',
                'unique_together': {('inscricao', 'fase')},
            },
        ),
    ]
